name: Rust

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env: 
        MARVEL_PUBLIC: ${{secrets.MARVEL_PUBLIC}}
        MARVEL_PRIVATE: ${{secrets.MARVEL_PRIVATE}}
      run: cargo test --verbose
